# Conference configurations
conferences:
  neurips:
    name: "Conference on Neural Information Processing Systems"
    short_name: "NeurIPS"
    strategy: "static_html"
    years_available: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
    rate_limit: 1

  icml:
    name: "International Conference on Machine Learning"
    short_name: "ICML"
    strategy: "static_html"
    years_available: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
    rate_limit: 1

  usenix_security:
    name: "USENIX Security Symposium"
    short_name: "USENIX Security"
    strategy: "static_html"
    years_available: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
    rate_limit: 1

  iclr:
    name: "International Conference on Learning Representations"
    short_name: "ICLR"
    strategy: "openreview"
    years_available: [2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
    rate_limit: 0.5
    openreview_invitations:
      2024: "ICLR.cc/2024/Conference/-/Submission"
      2023: "ICLR.cc/2023/Conference/-/Blind_Submission"
      2022: "ICLR.cc/2022/Conference/-/Blind_Submission"
      2021: "ICLR.cc/2021/Conference/-/Blind_Submission"
      2020: "ICLR.cc/2020/Conference/-/Blind_Submission"
      2019: "ICLR.cc/2019/Conference/-/Blind_Submission"
      2018: "ICLR.cc/2018/Conference/-/Blind_Submission"
      2017: "ICLR.cc/2017/conference/-/submission"
    filter_accepted_only: true

  icse:
    name: "International Conference on Software Engineering"
    short_name: "ICSE"
    strategy: "dblp_hybrid"
    years_available: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
    dblp_venue: "ICSE"
    rate_limit: 1.0
    enrichment:
      semantic_scholar: true

  fse:
    name: "Foundations of Software Engineering"
    short_name: "FSE"
    strategy: "dblp_hybrid"
    years_available: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
    dblp_venue: "SIGSOFT FSE"
    rate_limit: 1.0
    enrichment:
      semantic_scholar: true

  ase:
    name: "Automated Software Engineering"
    short_name: "ASE"
    strategy: "dblp_hybrid"
    years_available: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
    dblp_venue: "ASE"
    rate_limit: 1.0
    enrichment:
      semantic_scholar: true

  issta:
    name: "International Symposium on Software Testing and Analysis"
    short_name: "ISSTA"
    strategy: "dblp_hybrid"
    years_available: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
    dblp_venue: "ISSTA"
    rate_limit: 1.0
    enrichment:
      semantic_scholar: true

  ccs:
    name: "ACM Conference on Computer and Communications Security"
    short_name: "CCS"
    strategy: "dblp_hybrid"
    years_available: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
    dblp_venue: "CCS"
    rate_limit: 1.0
    enrichment:
      semantic_scholar: true

  sp:
    name: "IEEE Symposium on Security and Privacy"
    short_name: "S&P"
    strategy: "dblp_hybrid"
    years_available: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
    dblp_venue: "IEEE Symposium on Security and Privacy"
    rate_limit: 1.0
    enrichment:
      semantic_scholar: true
